baseURL = 'https://wuflyh.github.io/reading-notes'
locale = 'en-us'
title = "Fei's Paper Reading Notes"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
